version: '3'

services:
    backend: 
      build: backend/
      container_name: backend 

      command: python app.py
      
      ports:
        - 8080:8080

      depends_on:
        - mongodb
      

    mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: unless-stopped
      command: mongod --auth

      environment:
        MONGODB_DATA_DIR: /data/db
        MONDODB_LOG_DIR: /dev/null
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword

      ports:
        - 27017:27017

      volumes:
        - mongodb_data_cont:/datadb

volumes:
  mongodb_data_cont: